name : Statistician Test and Push

on:
  pull_request:
    branches:
      - main
    paths:
      - 'statistician/**'
      - '.github/workflows/statistician-*'
  push:
    branches:
      - main
    paths:
      - 'statistician/**'
      - '.github/workflows/statistician-*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Statistician image
      timeout-minutes: 20
      shell: bash
      run: |
        cd statistician
        docker-compose build

    - name: Run Dockerized Tests for Statistician
      timeout-minutes: 20
      shell: bash
      run: |
        cd statistician
        make test

  push:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get tag for this build if it exists
      run: |
        echo "VERSION=$(cat statistician/version.txt)" >> $GITHUB_ENV

    - name: Build and Push unstable Docker Image from PR / Push to Master
      uses: whoan/docker-build-with-cache-action@v4
      with:
        context: statistician
        image_name: ${{ env.IMAGE_NAME }}
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        image_tag: latest,${{ env.VERSION }}


    - name: Update Docker Hub Description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASS }}
        repository: ${{ env.IMAGE_NAME }}
        readme-filepath: ./statistician/readme.md
        short-description: Open Data Cube Statistician Image